# --- build stage ---
FROM public.ecr.aws/docker/library/node:lts-alpine3.22 AS build
WORKDIR /repo
RUN npm install -g pnpm@10.33.1

# copy minimal manifests for better cache
COPY pnpm-lock.yaml .
COPY package.json .
COPY pnpm-workspace.yaml .
COPY ./packages/ ./packages/
COPY ./services/uplink/uplink_processor_wrkr ./services/uplink/uplink_processor_wrkr
RUN pnpm install
RUN pnpm -r run build

# install only the service and its local workspace deps
RUN pnpm -r i --filter ./services/uplink/uplink_processor_wrkr --filter @road-citizen-inspector/schemas
RUN pnpm -r i --filter ./services/uplink/uplink_processor_wrkr --filter @road-citizen-inspector/models
RUN pnpm -r i --filter ./services/uplink/uplink_processor_wrkr --filter @road-citizen-inspector/contracts
RUN pnpm -r i --filter ./services/uplink/uplink_processor_wrkr --filter @road-citizen-inspector/uplink-processing-jobs
RUN pnpm -r i --filter ./services/uplink/uplink_processor_wrkr --filter @road-citizen-inspector/server-map
RUN pnpm -C ./services/uplink/uplink_processor_wrkr install
RUN pnpm -C ./services/uplink/uplink_processor_wrkr build

CMD ["node","./services/uplink/uplink_processor_wrkr/dist/index.js"]
