/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteRouteImport } from './routes/session.$sessionId/route'
import { Route as AuthorizationSessionIdRouteRouteImport } from './routes/authorization.$sessionId/route'
import { Route as AuthorizationSessionIdIndexRouteImport } from './routes/authorization.$sessionId/index'
import { Route as SessionSessionIdOnboardingRouteImport } from './routes/session.$sessionId/onboarding'
import { Route as AuthorizationSessionIdAdministratorRouteImport } from './routes/authorization.$sessionId/administrator'
import { Route as SessionSessionIdSettingsRouteRouteImport } from './routes/session.$sessionId/settings/route'
import { Route as SessionSessionIdClaimedRouteRouteImport } from './routes/session.$sessionId/_claimed/route'
import { Route as SessionSessionIdSettingsIndexRouteImport } from './routes/session.$sessionId/settings/index'
import { Route as SessionSessionIdClaimedIndexRouteImport } from './routes/session.$sessionId/_claimed/index'
import { Route as SessionSessionIdSettingsKeysRouteImport } from './routes/session.$sessionId/settings/keys'
import { Route as SessionSessionIdSettingsDevicesRouteImport } from './routes/session.$sessionId/settings/devices'
import { Route as SessionSessionIdClaimedRecordsRouteRouteImport } from './routes/session.$sessionId/_claimed/records/route'
import { Route as SessionSessionIdClaimedProjectRouteRouteImport } from './routes/session.$sessionId/_claimed/project/route'
import { Route as SessionSessionIdClaimedRecordsIndexRouteImport } from './routes/session.$sessionId/_claimed/records/index'
import { Route as SessionSessionIdClaimedProjectIndexRouteImport } from './routes/session.$sessionId/_claimed/project/index'
import { Route as SessionSessionIdClaimedDeviceIndexRouteImport } from './routes/session.$sessionId/_claimed/device/index'
import { Route as SessionSessionIdClaimedRecordsUplinksRouteImport } from './routes/session.$sessionId/_claimed/records/uplinks'
import { Route as SessionSessionIdClaimedRecordsStatusRouteImport } from './routes/session.$sessionId/_claimed/records/status'
import { Route as SessionSessionIdClaimedRecordsReadingsRouteImport } from './routes/session.$sessionId/_claimed/records/readings'
import { Route as SessionSessionIdClaimedProjectThemeriverRouteImport } from './routes/session.$sessionId/_claimed/project/themeriver'
import { Route as SessionSessionIdClaimedProjectHistogramRouteImport } from './routes/session.$sessionId/_claimed/project/histogram'
import { Route as SessionSessionIdClaimedDeviceDeviceIdRouteImport } from './routes/session.$sessionId/_claimed/device/$deviceId'

const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRouteRoute = SessionSessionIdRouteRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizationSessionIdRouteRoute =
  AuthorizationSessionIdRouteRouteImport.update({
    id: '/authorization/$sessionId',
    path: '/authorization/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthorizationSessionIdIndexRoute =
  AuthorizationSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizationSessionIdRouteRoute,
  } as any)
const SessionSessionIdOnboardingRoute =
  SessionSessionIdOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => SessionSessionIdRouteRoute,
  } as any)
const AuthorizationSessionIdAdministratorRoute =
  AuthorizationSessionIdAdministratorRouteImport.update({
    id: '/administrator',
    path: '/administrator',
    getParentRoute: () => AuthorizationSessionIdRouteRoute,
  } as any)
const SessionSessionIdSettingsRouteRoute =
  SessionSessionIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => SessionSessionIdRouteRoute,
  } as any)
const SessionSessionIdClaimedRouteRoute =
  SessionSessionIdClaimedRouteRouteImport.update({
    id: '/_claimed',
    getParentRoute: () => SessionSessionIdRouteRoute,
  } as any)
const SessionSessionIdSettingsIndexRoute =
  SessionSessionIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionSessionIdSettingsRouteRoute,
  } as any)
const SessionSessionIdClaimedIndexRoute =
  SessionSessionIdClaimedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionSessionIdClaimedRouteRoute,
  } as any)
const SessionSessionIdSettingsKeysRoute =
  SessionSessionIdSettingsKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => SessionSessionIdSettingsRouteRoute,
  } as any)
const SessionSessionIdSettingsDevicesRoute =
  SessionSessionIdSettingsDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => SessionSessionIdSettingsRouteRoute,
  } as any)
const SessionSessionIdClaimedRecordsRouteRoute =
  SessionSessionIdClaimedRecordsRouteRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => SessionSessionIdClaimedRouteRoute,
  } as any)
const SessionSessionIdClaimedProjectRouteRoute =
  SessionSessionIdClaimedProjectRouteRouteImport.update({
    id: '/project',
    path: '/project',
    getParentRoute: () => SessionSessionIdClaimedRouteRoute,
  } as any)
const SessionSessionIdClaimedRecordsIndexRoute =
  SessionSessionIdClaimedRecordsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionSessionIdClaimedRecordsRouteRoute,
  } as any)
const SessionSessionIdClaimedProjectIndexRoute =
  SessionSessionIdClaimedProjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionSessionIdClaimedProjectRouteRoute,
  } as any)
const SessionSessionIdClaimedDeviceIndexRoute =
  SessionSessionIdClaimedDeviceIndexRouteImport.update({
    id: '/device/',
    path: '/device/',
    getParentRoute: () => SessionSessionIdClaimedRouteRoute,
  } as any)
const SessionSessionIdClaimedRecordsUplinksRoute =
  SessionSessionIdClaimedRecordsUplinksRouteImport.update({
    id: '/uplinks',
    path: '/uplinks',
    getParentRoute: () => SessionSessionIdClaimedRecordsRouteRoute,
  } as any)
const SessionSessionIdClaimedRecordsStatusRoute =
  SessionSessionIdClaimedRecordsStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => SessionSessionIdClaimedRecordsRouteRoute,
  } as any)
const SessionSessionIdClaimedRecordsReadingsRoute =
  SessionSessionIdClaimedRecordsReadingsRouteImport.update({
    id: '/readings',
    path: '/readings',
    getParentRoute: () => SessionSessionIdClaimedRecordsRouteRoute,
  } as any)
const SessionSessionIdClaimedProjectThemeriverRoute =
  SessionSessionIdClaimedProjectThemeriverRouteImport.update({
    id: '/themeriver',
    path: '/themeriver',
    getParentRoute: () => SessionSessionIdClaimedProjectRouteRoute,
  } as any)
const SessionSessionIdClaimedProjectHistogramRoute =
  SessionSessionIdClaimedProjectHistogramRouteImport.update({
    id: '/histogram',
    path: '/histogram',
    getParentRoute: () => SessionSessionIdClaimedProjectRouteRoute,
  } as any)
const SessionSessionIdClaimedDeviceDeviceIdRoute =
  SessionSessionIdClaimedDeviceDeviceIdRouteImport.update({
    id: '/device/$deviceId',
    path: '/device/$deviceId',
    getParentRoute: () => SessionSessionIdClaimedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/authorization/$sessionId': typeof AuthorizationSessionIdRouteRouteWithChildren
  '/session/$sessionId': typeof SessionSessionIdClaimedRouteRouteWithChildren
  '/session/$sessionId/settings': typeof SessionSessionIdSettingsRouteRouteWithChildren
  '/authorization/$sessionId/administrator': typeof AuthorizationSessionIdAdministratorRoute
  '/session/$sessionId/onboarding': typeof SessionSessionIdOnboardingRoute
  '/authorization/$sessionId/': typeof AuthorizationSessionIdIndexRoute
  '/session/$sessionId/project': typeof SessionSessionIdClaimedProjectRouteRouteWithChildren
  '/session/$sessionId/records': typeof SessionSessionIdClaimedRecordsRouteRouteWithChildren
  '/session/$sessionId/settings/devices': typeof SessionSessionIdSettingsDevicesRoute
  '/session/$sessionId/settings/keys': typeof SessionSessionIdSettingsKeysRoute
  '/session/$sessionId/': typeof SessionSessionIdClaimedIndexRoute
  '/session/$sessionId/settings/': typeof SessionSessionIdSettingsIndexRoute
  '/session/$sessionId/device/$deviceId': typeof SessionSessionIdClaimedDeviceDeviceIdRoute
  '/session/$sessionId/project/histogram': typeof SessionSessionIdClaimedProjectHistogramRoute
  '/session/$sessionId/project/themeriver': typeof SessionSessionIdClaimedProjectThemeriverRoute
  '/session/$sessionId/records/readings': typeof SessionSessionIdClaimedRecordsReadingsRoute
  '/session/$sessionId/records/status': typeof SessionSessionIdClaimedRecordsStatusRoute
  '/session/$sessionId/records/uplinks': typeof SessionSessionIdClaimedRecordsUplinksRoute
  '/session/$sessionId/device': typeof SessionSessionIdClaimedDeviceIndexRoute
  '/session/$sessionId/project/': typeof SessionSessionIdClaimedProjectIndexRoute
  '/session/$sessionId/records/': typeof SessionSessionIdClaimedRecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/session/$sessionId': typeof SessionSessionIdClaimedIndexRoute
  '/authorization/$sessionId/administrator': typeof AuthorizationSessionIdAdministratorRoute
  '/session/$sessionId/onboarding': typeof SessionSessionIdOnboardingRoute
  '/authorization/$sessionId': typeof AuthorizationSessionIdIndexRoute
  '/session/$sessionId/settings/devices': typeof SessionSessionIdSettingsDevicesRoute
  '/session/$sessionId/settings/keys': typeof SessionSessionIdSettingsKeysRoute
  '/session/$sessionId/settings': typeof SessionSessionIdSettingsIndexRoute
  '/session/$sessionId/device/$deviceId': typeof SessionSessionIdClaimedDeviceDeviceIdRoute
  '/session/$sessionId/project/histogram': typeof SessionSessionIdClaimedProjectHistogramRoute
  '/session/$sessionId/project/themeriver': typeof SessionSessionIdClaimedProjectThemeriverRoute
  '/session/$sessionId/records/readings': typeof SessionSessionIdClaimedRecordsReadingsRoute
  '/session/$sessionId/records/status': typeof SessionSessionIdClaimedRecordsStatusRoute
  '/session/$sessionId/records/uplinks': typeof SessionSessionIdClaimedRecordsUplinksRoute
  '/session/$sessionId/device': typeof SessionSessionIdClaimedDeviceIndexRoute
  '/session/$sessionId/project': typeof SessionSessionIdClaimedProjectIndexRoute
  '/session/$sessionId/records': typeof SessionSessionIdClaimedRecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/authorization/$sessionId': typeof AuthorizationSessionIdRouteRouteWithChildren
  '/session/$sessionId': typeof SessionSessionIdRouteRouteWithChildren
  '/session/$sessionId/_claimed': typeof SessionSessionIdClaimedRouteRouteWithChildren
  '/session/$sessionId/settings': typeof SessionSessionIdSettingsRouteRouteWithChildren
  '/authorization/$sessionId/administrator': typeof AuthorizationSessionIdAdministratorRoute
  '/session/$sessionId/onboarding': typeof SessionSessionIdOnboardingRoute
  '/authorization/$sessionId/': typeof AuthorizationSessionIdIndexRoute
  '/session/$sessionId/_claimed/project': typeof SessionSessionIdClaimedProjectRouteRouteWithChildren
  '/session/$sessionId/_claimed/records': typeof SessionSessionIdClaimedRecordsRouteRouteWithChildren
  '/session/$sessionId/settings/devices': typeof SessionSessionIdSettingsDevicesRoute
  '/session/$sessionId/settings/keys': typeof SessionSessionIdSettingsKeysRoute
  '/session/$sessionId/_claimed/': typeof SessionSessionIdClaimedIndexRoute
  '/session/$sessionId/settings/': typeof SessionSessionIdSettingsIndexRoute
  '/session/$sessionId/_claimed/device/$deviceId': typeof SessionSessionIdClaimedDeviceDeviceIdRoute
  '/session/$sessionId/_claimed/project/histogram': typeof SessionSessionIdClaimedProjectHistogramRoute
  '/session/$sessionId/_claimed/project/themeriver': typeof SessionSessionIdClaimedProjectThemeriverRoute
  '/session/$sessionId/_claimed/records/readings': typeof SessionSessionIdClaimedRecordsReadingsRoute
  '/session/$sessionId/_claimed/records/status': typeof SessionSessionIdClaimedRecordsStatusRoute
  '/session/$sessionId/_claimed/records/uplinks': typeof SessionSessionIdClaimedRecordsUplinksRoute
  '/session/$sessionId/_claimed/device/': typeof SessionSessionIdClaimedDeviceIndexRoute
  '/session/$sessionId/_claimed/project/': typeof SessionSessionIdClaimedProjectIndexRoute
  '/session/$sessionId/_claimed/records/': typeof SessionSessionIdClaimedRecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generate'
    | '/authorization/$sessionId'
    | '/session/$sessionId'
    | '/session/$sessionId/settings'
    | '/authorization/$sessionId/administrator'
    | '/session/$sessionId/onboarding'
    | '/authorization/$sessionId/'
    | '/session/$sessionId/project'
    | '/session/$sessionId/records'
    | '/session/$sessionId/settings/devices'
    | '/session/$sessionId/settings/keys'
    | '/session/$sessionId/'
    | '/session/$sessionId/settings/'
    | '/session/$sessionId/device/$deviceId'
    | '/session/$sessionId/project/histogram'
    | '/session/$sessionId/project/themeriver'
    | '/session/$sessionId/records/readings'
    | '/session/$sessionId/records/status'
    | '/session/$sessionId/records/uplinks'
    | '/session/$sessionId/device'
    | '/session/$sessionId/project/'
    | '/session/$sessionId/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generate'
    | '/session/$sessionId'
    | '/authorization/$sessionId/administrator'
    | '/session/$sessionId/onboarding'
    | '/authorization/$sessionId'
    | '/session/$sessionId/settings/devices'
    | '/session/$sessionId/settings/keys'
    | '/session/$sessionId/settings'
    | '/session/$sessionId/device/$deviceId'
    | '/session/$sessionId/project/histogram'
    | '/session/$sessionId/project/themeriver'
    | '/session/$sessionId/records/readings'
    | '/session/$sessionId/records/status'
    | '/session/$sessionId/records/uplinks'
    | '/session/$sessionId/device'
    | '/session/$sessionId/project'
    | '/session/$sessionId/records'
  id:
    | '__root__'
    | '/'
    | '/generate'
    | '/authorization/$sessionId'
    | '/session/$sessionId'
    | '/session/$sessionId/_claimed'
    | '/session/$sessionId/settings'
    | '/authorization/$sessionId/administrator'
    | '/session/$sessionId/onboarding'
    | '/authorization/$sessionId/'
    | '/session/$sessionId/_claimed/project'
    | '/session/$sessionId/_claimed/records'
    | '/session/$sessionId/settings/devices'
    | '/session/$sessionId/settings/keys'
    | '/session/$sessionId/_claimed/'
    | '/session/$sessionId/settings/'
    | '/session/$sessionId/_claimed/device/$deviceId'
    | '/session/$sessionId/_claimed/project/histogram'
    | '/session/$sessionId/_claimed/project/themeriver'
    | '/session/$sessionId/_claimed/records/readings'
    | '/session/$sessionId/_claimed/records/status'
    | '/session/$sessionId/_claimed/records/uplinks'
    | '/session/$sessionId/_claimed/device/'
    | '/session/$sessionId/_claimed/project/'
    | '/session/$sessionId/_claimed/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateRoute: typeof GenerateRoute
  AuthorizationSessionIdRouteRoute: typeof AuthorizationSessionIdRouteRouteWithChildren
  SessionSessionIdRouteRoute: typeof SessionSessionIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorization/$sessionId': {
      id: '/authorization/$sessionId'
      path: '/authorization/$sessionId'
      fullPath: '/authorization/$sessionId'
      preLoaderRoute: typeof AuthorizationSessionIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorization/$sessionId/': {
      id: '/authorization/$sessionId/'
      path: '/'
      fullPath: '/authorization/$sessionId/'
      preLoaderRoute: typeof AuthorizationSessionIdIndexRouteImport
      parentRoute: typeof AuthorizationSessionIdRouteRoute
    }
    '/session/$sessionId/onboarding': {
      id: '/session/$sessionId/onboarding'
      path: '/onboarding'
      fullPath: '/session/$sessionId/onboarding'
      preLoaderRoute: typeof SessionSessionIdOnboardingRouteImport
      parentRoute: typeof SessionSessionIdRouteRoute
    }
    '/authorization/$sessionId/administrator': {
      id: '/authorization/$sessionId/administrator'
      path: '/administrator'
      fullPath: '/authorization/$sessionId/administrator'
      preLoaderRoute: typeof AuthorizationSessionIdAdministratorRouteImport
      parentRoute: typeof AuthorizationSessionIdRouteRoute
    }
    '/session/$sessionId/settings': {
      id: '/session/$sessionId/settings'
      path: '/settings'
      fullPath: '/session/$sessionId/settings'
      preLoaderRoute: typeof SessionSessionIdSettingsRouteRouteImport
      parentRoute: typeof SessionSessionIdRouteRoute
    }
    '/session/$sessionId/_claimed': {
      id: '/session/$sessionId/_claimed'
      path: ''
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdClaimedRouteRouteImport
      parentRoute: typeof SessionSessionIdRouteRoute
    }
    '/session/$sessionId/settings/': {
      id: '/session/$sessionId/settings/'
      path: '/'
      fullPath: '/session/$sessionId/settings/'
      preLoaderRoute: typeof SessionSessionIdSettingsIndexRouteImport
      parentRoute: typeof SessionSessionIdSettingsRouteRoute
    }
    '/session/$sessionId/_claimed/': {
      id: '/session/$sessionId/_claimed/'
      path: '/'
      fullPath: '/session/$sessionId/'
      preLoaderRoute: typeof SessionSessionIdClaimedIndexRouteImport
      parentRoute: typeof SessionSessionIdClaimedRouteRoute
    }
    '/session/$sessionId/settings/keys': {
      id: '/session/$sessionId/settings/keys'
      path: '/keys'
      fullPath: '/session/$sessionId/settings/keys'
      preLoaderRoute: typeof SessionSessionIdSettingsKeysRouteImport
      parentRoute: typeof SessionSessionIdSettingsRouteRoute
    }
    '/session/$sessionId/settings/devices': {
      id: '/session/$sessionId/settings/devices'
      path: '/devices'
      fullPath: '/session/$sessionId/settings/devices'
      preLoaderRoute: typeof SessionSessionIdSettingsDevicesRouteImport
      parentRoute: typeof SessionSessionIdSettingsRouteRoute
    }
    '/session/$sessionId/_claimed/records': {
      id: '/session/$sessionId/_claimed/records'
      path: '/records'
      fullPath: '/session/$sessionId/records'
      preLoaderRoute: typeof SessionSessionIdClaimedRecordsRouteRouteImport
      parentRoute: typeof SessionSessionIdClaimedRouteRoute
    }
    '/session/$sessionId/_claimed/project': {
      id: '/session/$sessionId/_claimed/project'
      path: '/project'
      fullPath: '/session/$sessionId/project'
      preLoaderRoute: typeof SessionSessionIdClaimedProjectRouteRouteImport
      parentRoute: typeof SessionSessionIdClaimedRouteRoute
    }
    '/session/$sessionId/_claimed/records/': {
      id: '/session/$sessionId/_claimed/records/'
      path: '/'
      fullPath: '/session/$sessionId/records/'
      preLoaderRoute: typeof SessionSessionIdClaimedRecordsIndexRouteImport
      parentRoute: typeof SessionSessionIdClaimedRecordsRouteRoute
    }
    '/session/$sessionId/_claimed/project/': {
      id: '/session/$sessionId/_claimed/project/'
      path: '/'
      fullPath: '/session/$sessionId/project/'
      preLoaderRoute: typeof SessionSessionIdClaimedProjectIndexRouteImport
      parentRoute: typeof SessionSessionIdClaimedProjectRouteRoute
    }
    '/session/$sessionId/_claimed/device/': {
      id: '/session/$sessionId/_claimed/device/'
      path: '/device'
      fullPath: '/session/$sessionId/device'
      preLoaderRoute: typeof SessionSessionIdClaimedDeviceIndexRouteImport
      parentRoute: typeof SessionSessionIdClaimedRouteRoute
    }
    '/session/$sessionId/_claimed/records/uplinks': {
      id: '/session/$sessionId/_claimed/records/uplinks'
      path: '/uplinks'
      fullPath: '/session/$sessionId/records/uplinks'
      preLoaderRoute: typeof SessionSessionIdClaimedRecordsUplinksRouteImport
      parentRoute: typeof SessionSessionIdClaimedRecordsRouteRoute
    }
    '/session/$sessionId/_claimed/records/status': {
      id: '/session/$sessionId/_claimed/records/status'
      path: '/status'
      fullPath: '/session/$sessionId/records/status'
      preLoaderRoute: typeof SessionSessionIdClaimedRecordsStatusRouteImport
      parentRoute: typeof SessionSessionIdClaimedRecordsRouteRoute
    }
    '/session/$sessionId/_claimed/records/readings': {
      id: '/session/$sessionId/_claimed/records/readings'
      path: '/readings'
      fullPath: '/session/$sessionId/records/readings'
      preLoaderRoute: typeof SessionSessionIdClaimedRecordsReadingsRouteImport
      parentRoute: typeof SessionSessionIdClaimedRecordsRouteRoute
    }
    '/session/$sessionId/_claimed/project/themeriver': {
      id: '/session/$sessionId/_claimed/project/themeriver'
      path: '/themeriver'
      fullPath: '/session/$sessionId/project/themeriver'
      preLoaderRoute: typeof SessionSessionIdClaimedProjectThemeriverRouteImport
      parentRoute: typeof SessionSessionIdClaimedProjectRouteRoute
    }
    '/session/$sessionId/_claimed/project/histogram': {
      id: '/session/$sessionId/_claimed/project/histogram'
      path: '/histogram'
      fullPath: '/session/$sessionId/project/histogram'
      preLoaderRoute: typeof SessionSessionIdClaimedProjectHistogramRouteImport
      parentRoute: typeof SessionSessionIdClaimedProjectRouteRoute
    }
    '/session/$sessionId/_claimed/device/$deviceId': {
      id: '/session/$sessionId/_claimed/device/$deviceId'
      path: '/device/$deviceId'
      fullPath: '/session/$sessionId/device/$deviceId'
      preLoaderRoute: typeof SessionSessionIdClaimedDeviceDeviceIdRouteImport
      parentRoute: typeof SessionSessionIdClaimedRouteRoute
    }
  }
}

interface AuthorizationSessionIdRouteRouteChildren {
  AuthorizationSessionIdAdministratorRoute: typeof AuthorizationSessionIdAdministratorRoute
  AuthorizationSessionIdIndexRoute: typeof AuthorizationSessionIdIndexRoute
}

const AuthorizationSessionIdRouteRouteChildren: AuthorizationSessionIdRouteRouteChildren =
  {
    AuthorizationSessionIdAdministratorRoute:
      AuthorizationSessionIdAdministratorRoute,
    AuthorizationSessionIdIndexRoute: AuthorizationSessionIdIndexRoute,
  }

const AuthorizationSessionIdRouteRouteWithChildren =
  AuthorizationSessionIdRouteRoute._addFileChildren(
    AuthorizationSessionIdRouteRouteChildren,
  )

interface SessionSessionIdClaimedProjectRouteRouteChildren {
  SessionSessionIdClaimedProjectHistogramRoute: typeof SessionSessionIdClaimedProjectHistogramRoute
  SessionSessionIdClaimedProjectThemeriverRoute: typeof SessionSessionIdClaimedProjectThemeriverRoute
  SessionSessionIdClaimedProjectIndexRoute: typeof SessionSessionIdClaimedProjectIndexRoute
}

const SessionSessionIdClaimedProjectRouteRouteChildren: SessionSessionIdClaimedProjectRouteRouteChildren =
  {
    SessionSessionIdClaimedProjectHistogramRoute:
      SessionSessionIdClaimedProjectHistogramRoute,
    SessionSessionIdClaimedProjectThemeriverRoute:
      SessionSessionIdClaimedProjectThemeriverRoute,
    SessionSessionIdClaimedProjectIndexRoute:
      SessionSessionIdClaimedProjectIndexRoute,
  }

const SessionSessionIdClaimedProjectRouteRouteWithChildren =
  SessionSessionIdClaimedProjectRouteRoute._addFileChildren(
    SessionSessionIdClaimedProjectRouteRouteChildren,
  )

interface SessionSessionIdClaimedRecordsRouteRouteChildren {
  SessionSessionIdClaimedRecordsReadingsRoute: typeof SessionSessionIdClaimedRecordsReadingsRoute
  SessionSessionIdClaimedRecordsStatusRoute: typeof SessionSessionIdClaimedRecordsStatusRoute
  SessionSessionIdClaimedRecordsUplinksRoute: typeof SessionSessionIdClaimedRecordsUplinksRoute
  SessionSessionIdClaimedRecordsIndexRoute: typeof SessionSessionIdClaimedRecordsIndexRoute
}

const SessionSessionIdClaimedRecordsRouteRouteChildren: SessionSessionIdClaimedRecordsRouteRouteChildren =
  {
    SessionSessionIdClaimedRecordsReadingsRoute:
      SessionSessionIdClaimedRecordsReadingsRoute,
    SessionSessionIdClaimedRecordsStatusRoute:
      SessionSessionIdClaimedRecordsStatusRoute,
    SessionSessionIdClaimedRecordsUplinksRoute:
      SessionSessionIdClaimedRecordsUplinksRoute,
    SessionSessionIdClaimedRecordsIndexRoute:
      SessionSessionIdClaimedRecordsIndexRoute,
  }

const SessionSessionIdClaimedRecordsRouteRouteWithChildren =
  SessionSessionIdClaimedRecordsRouteRoute._addFileChildren(
    SessionSessionIdClaimedRecordsRouteRouteChildren,
  )

interface SessionSessionIdClaimedRouteRouteChildren {
  SessionSessionIdClaimedProjectRouteRoute: typeof SessionSessionIdClaimedProjectRouteRouteWithChildren
  SessionSessionIdClaimedRecordsRouteRoute: typeof SessionSessionIdClaimedRecordsRouteRouteWithChildren
  SessionSessionIdClaimedIndexRoute: typeof SessionSessionIdClaimedIndexRoute
  SessionSessionIdClaimedDeviceDeviceIdRoute: typeof SessionSessionIdClaimedDeviceDeviceIdRoute
  SessionSessionIdClaimedDeviceIndexRoute: typeof SessionSessionIdClaimedDeviceIndexRoute
}

const SessionSessionIdClaimedRouteRouteChildren: SessionSessionIdClaimedRouteRouteChildren =
  {
    SessionSessionIdClaimedProjectRouteRoute:
      SessionSessionIdClaimedProjectRouteRouteWithChildren,
    SessionSessionIdClaimedRecordsRouteRoute:
      SessionSessionIdClaimedRecordsRouteRouteWithChildren,
    SessionSessionIdClaimedIndexRoute: SessionSessionIdClaimedIndexRoute,
    SessionSessionIdClaimedDeviceDeviceIdRoute:
      SessionSessionIdClaimedDeviceDeviceIdRoute,
    SessionSessionIdClaimedDeviceIndexRoute:
      SessionSessionIdClaimedDeviceIndexRoute,
  }

const SessionSessionIdClaimedRouteRouteWithChildren =
  SessionSessionIdClaimedRouteRoute._addFileChildren(
    SessionSessionIdClaimedRouteRouteChildren,
  )

interface SessionSessionIdSettingsRouteRouteChildren {
  SessionSessionIdSettingsDevicesRoute: typeof SessionSessionIdSettingsDevicesRoute
  SessionSessionIdSettingsKeysRoute: typeof SessionSessionIdSettingsKeysRoute
  SessionSessionIdSettingsIndexRoute: typeof SessionSessionIdSettingsIndexRoute
}

const SessionSessionIdSettingsRouteRouteChildren: SessionSessionIdSettingsRouteRouteChildren =
  {
    SessionSessionIdSettingsDevicesRoute: SessionSessionIdSettingsDevicesRoute,
    SessionSessionIdSettingsKeysRoute: SessionSessionIdSettingsKeysRoute,
    SessionSessionIdSettingsIndexRoute: SessionSessionIdSettingsIndexRoute,
  }

const SessionSessionIdSettingsRouteRouteWithChildren =
  SessionSessionIdSettingsRouteRoute._addFileChildren(
    SessionSessionIdSettingsRouteRouteChildren,
  )

interface SessionSessionIdRouteRouteChildren {
  SessionSessionIdClaimedRouteRoute: typeof SessionSessionIdClaimedRouteRouteWithChildren
  SessionSessionIdSettingsRouteRoute: typeof SessionSessionIdSettingsRouteRouteWithChildren
  SessionSessionIdOnboardingRoute: typeof SessionSessionIdOnboardingRoute
}

const SessionSessionIdRouteRouteChildren: SessionSessionIdRouteRouteChildren = {
  SessionSessionIdClaimedRouteRoute:
    SessionSessionIdClaimedRouteRouteWithChildren,
  SessionSessionIdSettingsRouteRoute:
    SessionSessionIdSettingsRouteRouteWithChildren,
  SessionSessionIdOnboardingRoute: SessionSessionIdOnboardingRoute,
}

const SessionSessionIdRouteRouteWithChildren =
  SessionSessionIdRouteRoute._addFileChildren(
    SessionSessionIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateRoute: GenerateRoute,
  AuthorizationSessionIdRouteRoute:
    AuthorizationSessionIdRouteRouteWithChildren,
  SessionSessionIdRouteRoute: SessionSessionIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
