# --- build stage ---
FROM public.ecr.aws/docker/library/node:lts-alpine3.22 AS build
WORKDIR /repo
RUN npm install -g pnpm@10.33.1

# copy minimal manifests for better cache
COPY pnpm-lock.yaml .
COPY package.json .
COPY pnpm-workspace.yaml .
COPY ./packages/ ./packages/
COPY ./services/gateway ./services/gateway
RUN pnpm install
RUN pnpm -r run build

# install only the service and its local workspace deps
RUN pnpm -r i --filter ./services/gateway --filter @road-citizen-inspector/schemas
RUN pnpm -r i --filter ./services/gateway --filter @road-citizen-inspector/password-strategy
RUN pnpm -r i --filter ./services/gateway --filter @road-citizen-inspector/models
RUN pnpm -r i --filter ./services/gateway --filter @road-citizen-inspector/contracts
RUN pnpm -r i --filter ./services/gateway --filter @road-citizen-inspector/server-map
RUN pnpm -C ./services/gateway install
RUN pnpm -C ./services/gateway build

ENV NODE_ENV=production

CMD ["node", "./services/gateway/dist/index.js"]

EXPOSE 4000
