worker_processes auto;

events {
  worker_connections 1024;
}

http {

  resolver 127.0.0.11 ipv6=off;

  upstream frontend_app_servers {
    zone frontend_app_srvs 64k;
    server frontend_app:3000 resolve;
  }

  upstream gateway_api_servers {
    zone gateway_api_srvs 64k;
    server gateway_api:4000 resolve;
  }

  upstream uplink_api_servers {
    zone uplink_api_srvs 64k;
    server uplink_api:4002 resolve;
  }

  server {
    listen 80;

    server_name www.static.rci.com static.rci.com;

    location / {
      alias /usr/src/app/public/;
    }
  }

  server {
    listen 443 ssl;

    ssl_certificate /run/secrets/tls_bundle;
    ssl_certificate_key /run/secrets/tls_key;
    server_name www.app.rci.com app.rci.com;

    location / {

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_http_version 1.1;
      proxy_pass http://frontend_app_servers/;
    }

    location ^~ /api/ {

      proxy_set_header Upgrade $http_upgrade;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;

      proxy_http_version 1.1;
      proxy_read_timeout 60s;

      proxy_pass http://gateway_api_servers/;
    }

    location ^~ /uplink {
      limit_except POST {
        deny all;
      }

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_http_version 1.1;
      proxy_set_header Connection "";

      proxy_pass http://uplink_api_servers;
    }

  }
}
