# --- build stage ---
FROM public.ecr.aws/docker/library/node:lts-alpine3.22 AS build
WORKDIR /repo
RUN npm install -g pnpm

# copy minimal manifests for better cache
COPY pnpm-lock.yaml .
COPY package.json .
COPY pnpm-workspace.yaml .
COPY ./packages/ ./packages/
COPY ./services/uplink/api ./services/uplink/api

RUN pnpm install
RUN pnpm -r run build

# install only the service and its local workspace deps
RUN pnpm -r i --filter ./services/uplink/api --filter @road-citizen-inspector/schemas
RUN pnpm -r i --filter ./services/uplink/api --filter @road-citizen-inspector/models
RUN pnpm -r i --filter ./services/uplink/api --filter @road-citizen-inspector/contracts
RUN pnpm -r i --filter ./services/uplink/api --filter @road-citizen-inspector/password-strategy
RUN pnpm -r i --filter ./services/uplink/api --filter @road-citizen-inspector/uplink-processing-jobs
RUN pnpm -r i --filter ./services/uplink/api --filter @road-citizen-inspector/session-expiry-jobs
RUN pnpm -r i --filter ./services/uplink/api --filter @road-citizen-inspector/server-map

RUN pnpm -C ./services/uplink/api install

RUN pnpm -C -r ./services/uplink/api build
CMD ["node", "./services/uplink/api/dist/index.js"]

EXPOSE 4002